#! /bin/sh

set -ex

dh_auto_configure -- \
    --disable-celt051 \
    --disable-silent-rules \
    --enable-smartcard
make -C subprojects/spice-common/common libspice-common.la libspice-common-server.la
make -C server libspice-server.la
make -C server/tests all
./server/tests/test-display-streaming  --automated-tests

