
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef SPICE_SERVER_ENUMS_H
#define SPICE_SERVER_ENUMS_H

G_BEGIN_DECLS
#define SPICE_TYPE_SPICE_COMPAT_VERSION_T spice_compat_version_t_spice_compat_version_t_get_type()
GType spice_compat_version_t_spice_compat_version_t_get_type (void);
#define SPICE_TYPE_SPICE_IMAGE_COMPRESSION_T spice_image_compression_t_spice_image_compression_t_get_type()
GType spice_image_compression_t_spice_image_compression_t_get_type (void);
#define SPICE_TYPE_SPICE_WAN_COMPRESSION_T spice_wan_compression_t_spice_wan_compression_t_get_type()
GType spice_wan_compression_t_spice_wan_compression_t_get_type (void);

G_END_DECLS

#endif /* SPICE_SERVER_ENUMS_H */

/* Generated data ends here */

